package co.ambulancia.demo.modelo;
// Generated 30/06/2017 08:43:08 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name = "medico", schema = "public")
public class Medico implements java.io.Serializable {

	private long mediCodigo;
	private String mediNombre;
	private Set<Remision> remisions = new HashSet<Remision>(0);

	public Medico() {
	}

	public Medico(long mediCodigo, String mediNombre) {
		this.mediCodigo = mediCodigo;
		this.mediNombre = mediNombre;
	}

	public Medico(long mediCodigo, String mediNombre, Set<Remision> remisions) {
		this.mediCodigo = mediCodigo;
		this.mediNombre = mediNombre;
		this.remisions = remisions;
	}

	@Id

	@Column(name = "medi_codigo", unique = true, nullable = false, precision = 10, scale = 0)
	public long getMediCodigo() {
		return this.mediCodigo;
	}

	public void setMediCodigo(long mediCodigo) {
		this.mediCodigo = mediCodigo;
	}

	@Column(name = "medi_nombre", nullable = false, length = 50)
	public String getMediNombre() {
		return this.mediNombre;
	}

	public void setMediNombre(String mediNombre) {
		this.mediNombre = mediNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medico")
	public Set<Remision> getRemisions() {
		return this.remisions;
	}

	public void setRemisions(Set<Remision> remisions) {
		this.remisions = remisions;
	}

}
