package co.ambulancia.demo.modelo;
// Generated 30/06/2017 08:43:08 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pacientes generated by hbm2java
 */
@Entity
@Table(name = "pacientes", schema = "public")
public class Pacientes implements java.io.Serializable {

	private String pacId;
	private TiposDocumentos tiposDocumentos;
	private String pacNombre;
	private byte pacEdad;
	private String pacNumHistoria;
	private String diagnostico;
	private Set<Remision> remisions = new HashSet<Remision>(0);

	public Pacientes() {
	}

	public Pacientes(String pacId, TiposDocumentos tiposDocumentos, String pacNombre, byte pacEdad,
			String pacNumHistoria) {
		this.pacId = pacId;
		this.tiposDocumentos = tiposDocumentos;
		this.pacNombre = pacNombre;
		this.pacEdad = pacEdad;
		this.pacNumHistoria = pacNumHistoria;
	}

	public Pacientes(String pacId, TiposDocumentos tiposDocumentos, String pacNombre, byte pacEdad,
			String pacNumHistoria, String diagnostico, Set<Remision> remisions) {
		this.pacId = pacId;
		this.tiposDocumentos = tiposDocumentos;
		this.pacNombre = pacNombre;
		this.pacEdad = pacEdad;
		this.pacNumHistoria = pacNumHistoria;
		this.diagnostico = diagnostico;
		this.remisions = remisions;
	}

	@Id

	@Column(name = "pac_id", unique = true, nullable = false, length = 20)
	public String getPacId() {
		return this.pacId;
	}

	public void setPacId(String pacId) {
		this.pacId = pacId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tdoc_codigo", nullable = false)
	public TiposDocumentos getTiposDocumentos() {
		return this.tiposDocumentos;
	}

	public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
		this.tiposDocumentos = tiposDocumentos;
	}

	@Column(name = "pac_nombre", nullable = false, length = 50)
	public String getPacNombre() {
		return this.pacNombre;
	}

	public void setPacNombre(String pacNombre) {
		this.pacNombre = pacNombre;
	}

	@Column(name = "pac_edad", nullable = false, precision = 2, scale = 0)
	public byte getPacEdad() {
		return this.pacEdad;
	}

	public void setPacEdad(byte pacEdad) {
		this.pacEdad = pacEdad;
	}

	@Column(name = "pac_num_historia", nullable = false, length = 20)
	public String getPacNumHistoria() {
		return this.pacNumHistoria;
	}

	public void setPacNumHistoria(String pacNumHistoria) {
		this.pacNumHistoria = pacNumHistoria;
	}

	@Column(name = "diagnostico")
	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pacientes")
	public Set<Remision> getRemisions() {
		return this.remisions;
	}

	public void setRemisions(Set<Remision> remisions) {
		this.remisions = remisions;
	}

}
