package co.ambulancia.demo.modelo;
// Generated 30/06/2017 08:43:08 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Remision generated by hbm2java
 */
@Entity
@Table(name = "remision", schema = "public")
public class Remision implements java.io.Serializable {

	private long remId;
	private Ambulancia ambulancia;
	private Medico medico;
	private Pacientes pacientes;
	private Prestador prestador;
	private Date remFecha;
	private Date remHora;
	private String codAutoriza;
	private String horaRecogida;
	private String horaCita;
	private String comentarios;
	private String remTras;
	private String remPerimetro;
	private String remLOrigen;
	private String remLDestino;
	private String remHSalida;
	private String remHLlegada;

	public Remision() {
	}

	public Remision(long remId, Ambulancia ambulancia, Medico medico, Pacientes pacientes, Prestador prestador,
			Date remFecha, Date remHora, String codAutoriza, String horaRecogida, String horaCita, String remTras,
			String remPerimetro, String remLOrigen, String remLDestino, String remHSalida, String remHLlegada) {
		this.remId = remId;
		this.ambulancia = ambulancia;
		this.medico = medico;
		this.pacientes = pacientes;
		this.prestador = prestador;
		this.remFecha = remFecha;
		this.remHora = remHora;
		this.codAutoriza = codAutoriza;
		this.horaRecogida = horaRecogida;
		this.horaCita = horaCita;
		this.remTras = remTras;
		this.remPerimetro = remPerimetro;
		this.remLOrigen = remLOrigen;
		this.remLDestino = remLDestino;
		this.remHSalida = remHSalida;
		this.remHLlegada = remHLlegada;
	}

	public Remision(long remId, Ambulancia ambulancia, Medico medico, Pacientes pacientes, Prestador prestador,
			Date remFecha, Date remHora, String codAutoriza, String horaRecogida, String horaCita, String comentarios,
			String remTras, String remPerimetro, String remLOrigen, String remLDestino, String remHSalida,
			String remHLlegada) {
		this.remId = remId;
		this.ambulancia = ambulancia;
		this.medico = medico;
		this.pacientes = pacientes;
		this.prestador = prestador;
		this.remFecha = remFecha;
		this.remHora = remHora;
		this.codAutoriza = codAutoriza;
		this.horaRecogida = horaRecogida;
		this.horaCita = horaCita;
		this.comentarios = comentarios;
		this.remTras = remTras;
		this.remPerimetro = remPerimetro;
		this.remLOrigen = remLOrigen;
		this.remLDestino = remLDestino;
		this.remHSalida = remHSalida;
		this.remHLlegada = remHLlegada;
	}

	@Id

	@Column(name = "rem_id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getRemId() {
		return this.remId;
	}

	public void setRemId(long remId) {
		this.remId = remId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "amb_id", nullable = false)
	public Ambulancia getAmbulancia() {
		return this.ambulancia;
	}

	public void setAmbulancia(Ambulancia ambulancia) {
		this.ambulancia = ambulancia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "med_id", nullable = false)
	public Medico getMedico() {
		return this.medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pac_id", nullable = false)
	public Pacientes getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Pacientes pacientes) {
		this.pacientes = pacientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tnit_prestador", nullable = false)
	public Prestador getPrestador() {
		return this.prestador;
	}

	public void setPrestador(Prestador prestador) {
		this.prestador = prestador;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rem_fecha", nullable = false, length = 13)
	public Date getRemFecha() {
		return this.remFecha;
	}

	public void setRemFecha(Date remFecha) {
		this.remFecha = remFecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "rem_hora", nullable = false, length = 15)
	public Date getRemHora() {
		return this.remHora;
	}

	public void setRemHora(Date remHora) {
		this.remHora = remHora;
	}

	@Column(name = "cod_autoriza", nullable = false, length = 50)
	public String getCodAutoriza() {
		return this.codAutoriza;
	}

	public void setCodAutoriza(String codAutoriza) {
		this.codAutoriza = codAutoriza;
	}

	@Column(name = "hora_recogida", nullable = false, length = 50)
	public String getHoraRecogida() {
		return this.horaRecogida;
	}

	public void setHoraRecogida(String horaRecogida) {
		this.horaRecogida = horaRecogida;
	}

	@Column(name = "hora_cita", nullable = false, length = 50)
	public String getHoraCita() {
		return this.horaCita;
	}

	public void setHoraCita(String horaCita) {
		this.horaCita = horaCita;
	}

	@Column(name = "comentarios")
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "rem_tras", nullable = false, length = 50)
	public String getRemTras() {
		return this.remTras;
	}

	public void setRemTras(String remTras) {
		this.remTras = remTras;
	}

	@Column(name = "rem_perimetro", nullable = false, length = 50)
	public String getRemPerimetro() {
		return this.remPerimetro;
	}

	public void setRemPerimetro(String remPerimetro) {
		this.remPerimetro = remPerimetro;
	}

	@Column(name = "rem_l_origen", nullable = false, length = 100)
	public String getRemLOrigen() {
		return this.remLOrigen;
	}

	public void setRemLOrigen(String remLOrigen) {
		this.remLOrigen = remLOrigen;
	}

	@Column(name = "rem_l_destino", nullable = false, length = 100)
	public String getRemLDestino() {
		return this.remLDestino;
	}

	public void setRemLDestino(String remLDestino) {
		this.remLDestino = remLDestino;
	}

	@Column(name = "rem_h_salida", nullable = false, length = 50)
	public String getRemHSalida() {
		return this.remHSalida;
	}

	public void setRemHSalida(String remHSalida) {
		this.remHSalida = remHSalida;
	}

	@Column(name = "rem_h_llegada", nullable = false, length = 50)
	public String getRemHLlegada() {
		return this.remHLlegada;
	}

	public void setRemHLlegada(String remHLlegada) {
		this.remHLlegada = remHLlegada;
	}

}
