package co.ambulancia.demo.modelo;
// Generated 30/06/2017 08:43:08 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Solicitante generated by hbm2java
 */
@Entity
@Table(name = "solicitante", schema = "public")
public class Solicitante implements java.io.Serializable {

	private long solId;
	private TiposDocumentos tiposDocumentos;
	private String solNombre;
	private String solDireccion;
	private String solTelefono;
	private String solMail;

	public Solicitante() {
	}

	public Solicitante(long solId, TiposDocumentos tiposDocumentos, String solNombre, String solDireccion,
			String solTelefono) {
		this.solId = solId;
		this.tiposDocumentos = tiposDocumentos;
		this.solNombre = solNombre;
		this.solDireccion = solDireccion;
		this.solTelefono = solTelefono;
	}

	public Solicitante(long solId, TiposDocumentos tiposDocumentos, String solNombre, String solDireccion,
			String solTelefono, String solMail) {
		this.solId = solId;
		this.tiposDocumentos = tiposDocumentos;
		this.solNombre = solNombre;
		this.solDireccion = solDireccion;
		this.solTelefono = solTelefono;
		this.solMail = solMail;
	}

	@Id

	@Column(name = "sol_id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getSolId() {
		return this.solId;
	}

	public void setSolId(long solId) {
		this.solId = solId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tdoc_codigo", nullable = false)
	public TiposDocumentos getTiposDocumentos() {
		return this.tiposDocumentos;
	}

	public void setTiposDocumentos(TiposDocumentos tiposDocumentos) {
		this.tiposDocumentos = tiposDocumentos;
	}

	@Column(name = "sol_nombre", nullable = false, length = 50)
	public String getSolNombre() {
		return this.solNombre;
	}

	public void setSolNombre(String solNombre) {
		this.solNombre = solNombre;
	}

	@Column(name = "sol_direccion", nullable = false, length = 50)
	public String getSolDireccion() {
		return this.solDireccion;
	}

	public void setSolDireccion(String solDireccion) {
		this.solDireccion = solDireccion;
	}

	@Column(name = "sol_telefono", nullable = false, length = 50)
	public String getSolTelefono() {
		return this.solTelefono;
	}

	public void setSolTelefono(String solTelefono) {
		this.solTelefono = solTelefono;
	}

	@Column(name = "sol_mail", length = 50)
	public String getSolMail() {
		return this.solMail;
	}

	public void setSolMail(String solMail) {
		this.solMail = solMail;
	}

}
