package co.ambulancia.demo.modelo;
// Generated 30/06/2017 08:43:08 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposDocumentos generated by hbm2java
 */
@Entity
@Table(name = "tipos_documentos", schema = "public")
public class TiposDocumentos implements java.io.Serializable {

	private long tdocCodigo;
	private String tdocNombre;
	private Set<Solicitante> solicitantes = new HashSet<Solicitante>(0);
	private Set<Pacientes> pacienteses = new HashSet<Pacientes>(0);

	public TiposDocumentos() {
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre, Set<Solicitante> solicitantes,
			Set<Pacientes> pacienteses) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
		this.solicitantes = solicitantes;
		this.pacienteses = pacienteses;
	}

	@Id

	@Column(name = "tdoc_codigo", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTdocCodigo() {
		return this.tdocCodigo;
	}

	public void setTdocCodigo(long tdocCodigo) {
		this.tdocCodigo = tdocCodigo;
	}

	@Column(name = "tdoc_nombre", nullable = false, length = 50)
	public String getTdocNombre() {
		return this.tdocNombre;
	}

	public void setTdocNombre(String tdocNombre) {
		this.tdocNombre = tdocNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposDocumentos")
	public Set<Solicitante> getSolicitantes() {
		return this.solicitantes;
	}

	public void setSolicitantes(Set<Solicitante> solicitantes) {
		this.solicitantes = solicitantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposDocumentos")
	public Set<Pacientes> getPacienteses() {
		return this.pacienteses;
	}

	public void setPacienteses(Set<Pacientes> pacienteses) {
		this.pacienteses = pacienteses;
	}

}
